name: fuel_type_repository
description: Dart package which manages the authentication domain.
version: 1.0.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
  http: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # mockito: ^4.0.0
